// CENTRAL EFC DATA SOURCE — regions, countries, member clubs, and team logos.
// Source: EFC official PDFs (Regions, Countries, Member Clubs).

export type Gender = "Men" | "Women";

export interface EfcClub {
  name: string;
  country: string;
  gender: Gender;
}

export interface EfcCountry {
  name: string;
  region: string;
  uefaRank?: number;
}

export const EFC_REGIONS: string[] = [
  "Southeast Europe",
  "British Isles",
  "German-Speaking Core",
  "Eurasian",
  "Benelux",
  "Central Europe",
  "Scandinavia",
  "Central-South Europe",
  "Eastern Europe",
  "Iberia",
];

export const COUNTRY_TO_REGION: Record<string, string> = {
  "Albania": "Southeast Europe",
  "Bosnia and Herzegovina": "Southeast Europe",
  "Bulgaria": "Southeast Europe",
  "Croatia": "Southeast Europe",
  "Cyprus": "Southeast Europe",
  "Greece": "Southeast Europe",
  "Kosovo": "Southeast Europe",
  "Montenegro": "Southeast Europe",
  "North Macedonia": "Southeast Europe",
  "Serbia": "Southeast Europe",
  "Slovenia": "Southeast Europe",
  "England": "British Isles",
  "Ireland": "British Isles",
  "Northern Ireland": "British Isles",
  "Scotland": "British Isles",
  "Wales": "British Isles",
  "Austria": "German-Speaking Core",
  "Germany": "German-Speaking Core",
  "Liechtenstein": "German-Speaking Core",
  "Switzerland": "German-Speaking Core",
  "Armenia": "Eurasian",
  "Azerbaijan": "Eurasian",
  "Belarus": "Eurasian",
  "Georgia": "Eurasian",
  "Israel": "Eurasian",
  "Kazakhstan": "Eurasian",
  "Russia": "Eurasian",
  "Turkey": "Eurasian",
  "Belgium": "Benelux",
  "Luxembourg": "Benelux",
  "Netherlands": "Benelux",
  "Czech Republic": "Central Europe",
  "Hungary": "Central Europe",
  "Poland": "Central Europe",
  "Slovakia": "Central Europe",
  "Denmark": "Scandinavia",
  "Faroe Islands": "Scandinavia",
  "Finland": "Scandinavia",
  "Iceland": "Scandinavia",
  "Norway": "Scandinavia",
  "Sweden": "Scandinavia",
  "France": "Central-South Europe",
  "Italy": "Central-South Europe",
  "Malta": "Central-South Europe",
  "San Marino": "Central-South Europe",
  "Estonia": "Eastern Europe",
  "Latvia": "Eastern Europe",
  "Lithuania": "Eastern Europe",
  "Moldova": "Eastern Europe",
  "Romania": "Eastern Europe",
  "Ukraine": "Eastern Europe",
  "Andorra": "Iberia",
  "Gibraltar": "Iberia",
  "Portugal": "Iberia",
  "Spain": "Iberia",
};

export const UEFA_RANK: Record<string, number> = {
  "England": 1,
  "Spain": 2,
  "Italy": 3,
  "Germany": 4,
  "Netherlands": 5,
  "France": 6,
  "Portugal": 7,
  "Belgium": 8,
  "Scotland": 9,
  "Austria": 10,
  "Switzerland": 11,
  "Turkey": 12,
  "Serbia": 13,
  "Ukraine": 14,
  "Norway": 15,
  "Denmark": 16,
  "Czech Republic": 17,
  "Israel": 18,
  "Greece": 19,
  "Croatia": 20,
  "Sweden": 21,
  "Russia": 22,
  "Poland": 23,
  "Cyprus": 24,
  "Romania": 25,
  "Hungary": 26,
  "Bulgaria": 27,
  "Slovakia": 28,
  "Azerbaijan": 29,
  "Moldova": 30,
  "Liechtenstein": 31,
  "Ireland": 32,
  "Finland": 33,
  "Slovenia": 34,
  "Latvia": 35,
  "Kosovo": 36,
  "Armenia": 37,
  "Kazakhstan": 38,
  "Northern Ireland": 39,
  "Bosnia and Herzegovina": 40,
  "Faroe Islands": 41,
  "Lithuania": 42,
  "Estonia": 43,
  "Malta": 44,
  "Luxembourg": 45,
  "Georgia": 46,
  "Iceland": 47,
  "Albania": 48,
  "Wales": 49,
  "Belarus": 50,
  "Gibraltar": 51,
  "North Macedonia": 52,
  "Montenegro": 53,
  "Andorra": 54,
  "San Marino": 55,
};

export const EFC_COUNTRIES: EfcCountry[] = [
  { name: "Albania", region: "Southeast Europe", uefaRank: 48 },
  { name: "Andorra", region: "Iberia", uefaRank: 54 },
  { name: "Armenia", region: "Eurasian", uefaRank: 37 },
  { name: "Austria", region: "German-Speaking Core", uefaRank: 10 },
  { name: "Azerbaijan", region: "Eurasian", uefaRank: 29 },
  { name: "Belarus", region: "Eurasian", uefaRank: 50 },
  { name: "Belgium", region: "Benelux", uefaRank: 8 },
  { name: "Bosnia and Herzegovina", region: "Southeast Europe", uefaRank: 40 },
  { name: "Bulgaria", region: "Southeast Europe", uefaRank: 27 },
  { name: "Croatia", region: "Southeast Europe", uefaRank: 20 },
  { name: "Cyprus", region: "Southeast Europe", uefaRank: 24 },
  { name: "Czech Republic", region: "Central Europe", uefaRank: 17 },
  { name: "Denmark", region: "Scandinavia", uefaRank: 16 },
  { name: "England", region: "British Isles", uefaRank: 1 },
  { name: "Estonia", region: "Eastern Europe", uefaRank: 43 },
  { name: "Faroe Islands", region: "Scandinavia", uefaRank: 41 },
  { name: "Finland", region: "Scandinavia", uefaRank: 33 },
  { name: "France", region: "Central-South Europe", uefaRank: 6 },
  { name: "Georgia", region: "Eurasian", uefaRank: 46 },
  { name: "Germany", region: "German-Speaking Core", uefaRank: 4 },
  { name: "Gibraltar", region: "Iberia", uefaRank: 51 },
  { name: "Greece", region: "Southeast Europe", uefaRank: 19 },
  { name: "Hungary", region: "Central Europe", uefaRank: 26 },
  { name: "Iceland", region: "Scandinavia", uefaRank: 47 },
  { name: "Ireland", region: "British Isles", uefaRank: 32 },
  { name: "Israel", region: "Eurasian", uefaRank: 18 },
  { name: "Italy", region: "Central-South Europe", uefaRank: 3 },
  { name: "Kazakhstan", region: "Eurasian", uefaRank: 38 },
  { name: "Kosovo", region: "Southeast Europe", uefaRank: 36 },
  { name: "Latvia", region: "Eastern Europe", uefaRank: 35 },
  { name: "Liechtenstein", region: "German-Speaking Core", uefaRank: 31 },
  { name: "Lithuania", region: "Eastern Europe", uefaRank: 42 },
  { name: "Luxembourg", region: "Benelux", uefaRank: 45 },
  { name: "Malta", region: "Central-South Europe", uefaRank: 44 },
  { name: "Moldova", region: "Eastern Europe", uefaRank: 30 },
  { name: "Montenegro", region: "Southeast Europe", uefaRank: 53 },
  { name: "Netherlands", region: "Benelux", uefaRank: 5 },
  { name: "North Macedonia", region: "Southeast Europe", uefaRank: 52 },
  { name: "Northern Ireland", region: "British Isles", uefaRank: 39 },
  { name: "Norway", region: "Scandinavia", uefaRank: 15 },
  { name: "Poland", region: "Central Europe", uefaRank: 23 },
  { name: "Portugal", region: "Iberia", uefaRank: 7 },
  { name: "Romania", region: "Eastern Europe", uefaRank: 25 },
  { name: "Russia", region: "Eurasian", uefaRank: 22 },
  { name: "San Marino", region: "Central-South Europe", uefaRank: 55 },
  { name: "Scotland", region: "British Isles", uefaRank: 9 },
  { name: "Serbia", region: "Southeast Europe", uefaRank: 13 },
  { name: "Slovakia", region: "Central Europe", uefaRank: 28 },
  { name: "Slovenia", region: "Southeast Europe", uefaRank: 34 },
  { name: "Spain", region: "Iberia", uefaRank: 2 },
  { name: "Sweden", region: "Scandinavia", uefaRank: 21 },
  { name: "Switzerland", region: "German-Speaking Core", uefaRank: 11 },
  { name: "Turkey", region: "Eurasian", uefaRank: 12 },
  { name: "Ukraine", region: "Eastern Europe", uefaRank: 14 },
  { name: "Wales", region: "British Isles", uefaRank: 49 },
];

export const EFC_COUNTRY_NAMES: string[] = EFC_COUNTRIES.map((c) => c.name);

export const EFC_CLUBS: EfcClub[] = [
  { name: "FK Apolonia", country: "Albania", gender: "Men" },
  { name: "FK Kukësi", country: "Albania", gender: "Men" },
  { name: "FK Partizani", country: "Albania", gender: "Men" },
  { name: "KF Erzeni", country: "Albania", gender: "Men" },
  { name: "KF Laçi", country: "Albania", gender: "Men" },
  { name: "KF Tirana", country: "Albania", gender: "Men" },
  { name: "FC Kinostudio", country: "Albania", gender: "Women" },
  { name: "KF Vllaznia Shkodra", country: "Albania", gender: "Women" },
  { name: "CE Carroi", country: "Andorra", gender: "Men" },
  { name: "CF Atletic America", country: "Andorra", gender: "Men" },
  { name: "CF Esperanca de Andorra", country: "Andorra", gender: "Men" },
  { name: "FC Ordino", country: "Andorra", gender: "Men" },
  { name: "FC Santa Coloma", country: "Andorra", gender: "Men" },
  { name: "FS La Massana", country: "Andorra", gender: "Men" },
  { name: "Inter Club d'Escaldes", country: "Andorra", gender: "Men" },
  { name: "Pas de la Casa", country: "Andorra", gender: "Men" },
  { name: "UE Sant Julià", country: "Andorra", gender: "Men" },
  { name: "UE Santa Coloma", country: "Andorra", gender: "Men" },
  { name: "Alashkert FC", country: "Armenia", gender: "Men" },
  { name: "FC Ararat", country: "Armenia", gender: "Men" },
  { name: "FC Ararat-Armenia", country: "Armenia", gender: "Men" },
  { name: "FC Gandzasar", country: "Armenia", gender: "Men" },
  { name: "FC Noah", country: "Armenia", gender: "Men" },
  { name: "FC Pyunik", country: "Armenia", gender: "Men" },
  { name: "FC Shirak", country: "Armenia", gender: "Men" },
  { name: "FC Urartu", country: "Armenia", gender: "Men" },
  { name: "FC West Armenia", country: "Armenia", gender: "Men" },
  { name: "FK Van", country: "Armenia", gender: "Men" },
  { name: "Syunik FC", country: "Armenia", gender: "Men" },
  { name: "Admira Wacker", country: "Austria", gender: "Men" },
  { name: "FC Blau-Weiss Linz", country: "Austria", gender: "Men" },
  { name: "FC Salzburg", country: "Austria", gender: "Men" },
  { name: "FK Austria Wien", country: "Austria", gender: "Men" },
  { name: "GAK 1902", country: "Austria", gender: "Men" },
  { name: "LASK", country: "Austria", gender: "Men" },
  { name: "SCR Altach", country: "Austria", gender: "Men" },
  { name: "SK Austria Klagenfurt", country: "Austria", gender: "Men" },
  { name: "SK Rapid", country: "Austria", gender: "Men" },
  { name: "SK Sturm Graz", country: "Austria", gender: "Men" },
  { name: "SV Oberbank Ried", country: "Austria", gender: "Men" },
  { name: "Wolfsberger AC", country: "Austria", gender: "Men" },
  { name: "SKN St. Pölten Frauen", country: "Austria", gender: "Women" },
  { name: "Araz-Nakhçhivan PFK", country: "Azerbaijan", gender: "Men" },
  { name: "FK Sabail", country: "Azerbaijan", gender: "Men" },
  { name: "Gabala SC", country: "Azerbaijan", gender: "Men" },
  { name: "Imishli PFC", country: "Azerbaijan", gender: "Men" },
  { name: "Käpäz PFK", country: "Azerbaijan", gender: "Men" },
  { name: "Karvan-Yevlax Football Club", country: "Azerbaijan", gender: "Men" },
  { name: "Neftçi PFK", country: "Azerbaijan", gender: "Men" },
  { name: "PFC Zire", country: "Azerbaijan", gender: "Men" },
  { name: "Qarabağ FK", country: "Azerbaijan", gender: "Men" },
  { name: "Sabah", country: "Azerbaijan", gender: "Men" },
  { name: "Sumqayıt FK", country: "Azerbaijan", gender: "Men" },
  { name: "Turan Tovuz PFK", country: "Azerbaijan", gender: "Men" },
  { name: "FC Arsenal Dzerzhinsk", country: "Belarus", gender: "Men" },
  { name: "FC BATE Borisov", country: "Belarus", gender: "Men" },
  { name: "FC Belshina", country: "Belarus", gender: "Men" },
  { name: "FC Dinamo Minsk", country: "Belarus", gender: "Men" },
  { name: "FC Dnepr Mogilev", country: "Belarus", gender: "Men" },
  { name: "FC Dynamo Brest", country: "Belarus", gender: "Men" },
  { name: "FC Energetik-BSU Minsk", country: "Belarus", gender: "Men" },
  { name: "FC Gomel", country: "Belarus", gender: "Men" },
  { name: "FC Isloch", country: "Belarus", gender: "Men" },
  { name: "FC ML Vitebsk", country: "Belarus", gender: "Men" },
  { name: "FC Neman Grodno", country: "Belarus", gender: "Men" },
  { name: "FC Shakhter Soligorsk", country: "Belarus", gender: "Men" },
  { name: "FC Smorgon", country: "Belarus", gender: "Men" },
  { name: "FC TORPEDO-BELAZ", country: "Belarus", gender: "Men" },
  { name: "FC Vitebsk", country: "Belarus", gender: "Men" },
  { name: "SFC Slutsk", country: "Belarus", gender: "Men" },
  { name: "FC Minsk", country: "Belarus", gender: "Women" },
  { name: "SKA-1938", country: "Belarus", gender: "Women" },
  { name: "WFC ABFF WU-19", country: "Belarus", gender: "Women" },
  { name: "WFC DUSSH-PolesSu", country: "Belarus", gender: "Women" },
  { name: "Cercle Brugge KSV", country: "Belgium", gender: "Men" },
  { name: "Club Brugge", country: "Belgium", gender: "Men" },
  { name: "FC Dender", country: "Belgium", gender: "Men" },
  { name: "KAA Gent", country: "Belgium", gender: "Men" },
  { name: "KAS Eupen", country: "Belgium", gender: "Men" },
  { name: "KRC Genk", country: "Belgium", gender: "Men" },
  { name: "KV Kortrijk (KVK)", country: "Belgium", gender: "Men" },
  { name: "KV Mechelen", country: "Belgium", gender: "Men" },
  { name: "KVC Westerlo", country: "Belgium", gender: "Men" },
  { name: "Oud-Heverlee Leuven", country: "Belgium", gender: "Men" },
  { name: "R. Standard de Liège", country: "Belgium", gender: "Men" },
  { name: "Royal Antwerp FC", country: "Belgium", gender: "Men" },
  { name: "Royal Charleroi SC", country: "Belgium", gender: "Men" },
  { name: "RWDM Brussels", country: "Belgium", gender: "Men" },
  { name: "Sint-Truidense VV (STVV)", country: "Belgium", gender: "Men" },
  { name: "RSC Anderlecht", country: "Belgium", gender: "Women" },
  { name: "FK Borac Banja Luka", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Igman Konjic", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Sloga Doboj", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Tuzla City", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Velež Mostar", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Željezničar", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Zvijezda 09", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "HŠK Posušje", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "HŠK Zrinjski", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "NK GOŠK Gabela", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "NK Široki Brijeg", country: "Bosnia and Herzegovina", gender: "Men" },
  { name: "FK Sarajevo", country: "Bosnia and Herzegovina", gender: "Women" },
  { name: "ŽF/NK Emina", country: "Bosnia and Herzegovina", gender: "Women" },
  { name: "ZFK Leotar Trebinje", country: "Bosnia and Herzegovina", gender: "Women" },
  { name: "CSKA 1948 Sofia", country: "Bulgaria", gender: "Men" },
  { name: "FC Dobrudja 1919", country: "Bulgaria", gender: "Men" },
  { name: "FC Etar VT", country: "Bulgaria", gender: "Men" },
  { name: "FC Hebar Pazardzhik", country: "Bulgaria", gender: "Men" },
  { name: "FC Lokomotiv Sofia 1929", country: "Bulgaria", gender: "Men" },
  { name: "FC Spartak Varna 1918", country: "Bulgaria", gender: "Men" },
  { name: "OFC Botev Vratsa", country: "Bulgaria", gender: "Men" },
  { name: "PFC Arda Kardzhali 1924", country: "Bulgaria", gender: "Men" },
  { name: "PFC Beroe Stara Zagora", country: "Bulgaria", gender: "Men" },
  { name: "PFC Botev Plovdiv", country: "Bulgaria", gender: "Men" },
  { name: "PFC Cherno More Varna", country: "Bulgaria", gender: "Men" },
  { name: "PFC CSKA Sofia", country: "Bulgaria", gender: "Men" },
  { name: "PFC Levski Sofia", country: "Bulgaria", gender: "Men" },
  { name: "PFC Lokomotiv Plovdiv 1926", country: "Bulgaria", gender: "Men" },
  { name: "PFC Ludogorets 1945", country: "Bulgaria", gender: "Men" },
  { name: "PFC Septemvri Sofia", country: "Bulgaria", gender: "Men" },
  { name: "PFC Slavia Sofia", country: "Bulgaria", gender: "Men" },
  { name: "Pirin Blagoevgrad", country: "Bulgaria", gender: "Men" },
  { name: "FC Dunav Ruse", country: "Bulgaria", gender: "Women" },
  { name: "FC NSA", country: "Bulgaria", gender: "Women" },
  { name: "FC Sevlievo Ladies", country: "Bulgaria", gender: "Women" },
  { name: "FC Sportika Blagoevgrad", country: "Bulgaria", gender: "Women" },
  { name: "FK Paldin Plovdiv", country: "Bulgaria", gender: "Women" },
  { name: "FK Svetkavitsa Gradezhnitsa", country: "Bulgaria", gender: "Women" },
  { name: "GNK Dinamo Zagreb", country: "Croatia", gender: "Men" },
  { name: "HNK Gorica", country: "Croatia", gender: "Men" },
  { name: "HNK Hajduk Split", country: "Croatia", gender: "Men" },
  { name: "HNK Rijeka", country: "Croatia", gender: "Men" },
  { name: "NK Istra 1961", country: "Croatia", gender: "Men" },
  { name: "NK Osijek", country: "Croatia", gender: "Men" },
  { name: "NK Rudeš", country: "Croatia", gender: "Men" },
  { name: "NK Slaven Belupo", country: "Croatia", gender: "Men" },
  { name: "NK Varaždin", country: "Croatia", gender: "Men" },
  { name: "ŽNK Agram", country: "Croatia", gender: "Women" },
  { name: "ZNK Dinamo Zagreb", country: "Croatia", gender: "Women" },
  { name: "ŽNK Donat-Zadar", country: "Croatia", gender: "Women" },
  { name: "ŽNK Medimurje", country: "Croatia", gender: "Women" },
  { name: "ZNK Split", country: "Croatia", gender: "Women" },
  { name: "AEK Larnaca FC", country: "Cyprus", gender: "Men" },
  { name: "AEL Limassol FC", country: "Cyprus", gender: "Men" },
  { name: "AEZ Zakakiou FC", country: "Cyprus", gender: "Men" },
  { name: "Akritas Chlorakas FC", country: "Cyprus", gender: "Men" },
  { name: "Anorthosis Famagusta FC", country: "Cyprus", gender: "Men" },
  { name: "APOEL FC", country: "Cyprus", gender: "Men" },
  { name: "Apollon Limassol FC", country: "Cyprus", gender: "Men" },
  { name: "Aris Limassol FC", country: "Cyprus", gender: "Men" },
  { name: "Ethnikos Achnas FC", country: "Cyprus", gender: "Men" },
  { name: "Karmiotissa FC", country: "Cyprus", gender: "Men" },
  { name: "Nea Salamis", country: "Cyprus", gender: "Men" },
  { name: "Olympiakos Nicosia", country: "Cyprus", gender: "Men" },
  { name: "Omonia Aradippou", country: "Cyprus", gender: "Men" },
  { name: "Omonoia FC", country: "Cyprus", gender: "Men" },
  { name: "PAC Omonia 29M", country: "Cyprus", gender: "Men" },
  { name: "Pafos FC", country: "Cyprus", gender: "Men" },
  { name: "Chrysomilia Agios Amvrosios Kyrenia", country: "Cyprus", gender: "Women" },
  { name: "Lakatamia FC", country: "Cyprus", gender: "Women" },
  { name: "Lefkothea", country: "Cyprus", gender: "Women" },
  { name: "1. FC Slovácko", country: "Czech Republic", gender: "Men" },
  { name: "AC Sparta Praha", country: "Czech Republic", gender: "Men" },
  { name: "Bohemians Praha 1905", country: "Czech Republic", gender: "Men" },
  { name: "FC Baník Ostrava", country: "Czech Republic", gender: "Men" },
  { name: "FC Hradec Králové", country: "Czech Republic", gender: "Men" },
  { name: "FC Slovan Liberec", country: "Czech Republic", gender: "Men" },
  { name: "FC Viktoria Plzeň", country: "Czech Republic", gender: "Men" },
  { name: "FC Zlin", country: "Czech Republic", gender: "Men" },
  { name: "FK Jablonec", country: "Czech Republic", gender: "Men" },
  { name: "FK Mladá Boleslav", country: "Czech Republic", gender: "Men" },
  { name: "FK Pardubice", country: "Czech Republic", gender: "Men" },
  { name: "FK Teplice", country: "Czech Republic", gender: "Men" },
  { name: "MFK Karviná", country: "Czech Republic", gender: "Men" },
  { name: "SK České Budějovice", country: "Czech Republic", gender: "Men" },
  { name: "SK Sigma Olomouc", country: "Czech Republic", gender: "Men" },
  { name: "SK Slavia Praha", country: "Czech Republic", gender: "Men" },
  { name: "Aalborg BK", country: "Denmark", gender: "Men" },
  { name: "AC Horsens", country: "Denmark", gender: "Men" },
  { name: "Brøndby IF", country: "Denmark", gender: "Men" },
  { name: "Esbjerg fB", country: "Denmark", gender: "Men" },
  { name: "FC Copenhagen", country: "Denmark", gender: "Men" },
  { name: "FC Midtjylland", country: "Denmark", gender: "Men" },
  { name: "FC Nordsjælland", country: "Denmark", gender: "Men" },
  { name: "Odense BK", country: "Denmark", gender: "Men" },
  { name: "Silkeborg IF", country: "Denmark", gender: "Men" },
  { name: "AGF Aarhus", country: "Denmark", gender: "Women" },
  { name: "Boldklubben af 1893", country: "Denmark", gender: "Women" },
  { name: "Fortuna Hjørring", country: "Denmark", gender: "Women" },
  { name: "HB Køge Women", country: "Denmark", gender: "Women" },
  { name: "AFC Bournemouth", country: "England", gender: "Men" },
  { name: "Arsenal FC", country: "England", gender: "Men" },
  { name: "Aston Villa FC", country: "England", gender: "Men" },
  { name: "Brentford FC", country: "England", gender: "Men" },
  { name: "Brighton & Hove Albion FC", country: "England", gender: "Men" },
  { name: "Chelsea FC", country: "England", gender: "Men" },
  { name: "Everton FC", country: "England", gender: "Men" },
  { name: "Fulham FC", country: "England", gender: "Men" },
  { name: "Leeds United FC", country: "England", gender: "Men" },
  { name: "Leicester City FC", country: "England", gender: "Men" },
  { name: "Liverpool FC", country: "England", gender: "Men" },
  { name: "Manchester City FC", country: "England", gender: "Men" },
  { name: "Manchester United FC", country: "England", gender: "Men" },
  { name: "Newcastle United FC", country: "England", gender: "Men" },
  { name: "Nottingham Forest FC", country: "England", gender: "Men" },
  { name: "Sunderland AFC", country: "England", gender: "Men" },
  { name: "Tottenham Hotspur", country: "England", gender: "Men" },
  { name: "West Ham United FC", country: "England", gender: "Men" },
  { name: "London City Lionesses", country: "England", gender: "Women" },
  { name: "FC Flora Tallinn", country: "Estonia", gender: "Men" },
  { name: "FC Kuressaare", country: "Estonia", gender: "Men" },
  { name: "FC Nõmme United", country: "Estonia", gender: "Men" },
  { name: "FCI Levadia Tallinn", country: "Estonia", gender: "Men" },
  { name: "Harju JK Laagri", country: "Estonia", gender: "Men" },
  { name: "JK Narva Trans", country: "Estonia", gender: "Men" },
  { name: "JK Tallinna Kalev", country: "Estonia", gender: "Men" },
  { name: "JK Tammeka Tartu", country: "Estonia", gender: "Men" },
  { name: "Nõmme Kalju FC", country: "Estonia", gender: "Men" },
  { name: "Paide Linnameeskond", country: "Estonia", gender: "Men" },
  { name: "Pärnu JK Vaprus", country: "Estonia", gender: "Men" },
  { name: "FC Ararat Tallinn", country: "Estonia", gender: "Women" },
  { name: "07 Vestur", country: "Faroe Islands", gender: "Men" },
  { name: "B36 Tórshavn", country: "Faroe Islands", gender: "Men" },
  { name: "B68 Toftir", country: "Faroe Islands", gender: "Men" },
  { name: "EB/Streymur", country: "Faroe Islands", gender: "Men" },
  { name: "HB Tórshavn", country: "Faroe Islands", gender: "Men" },
  { name: "KÍ Klaksvík", country: "Faroe Islands", gender: "Men" },
  { name: "NSÍ Runavík", country: "Faroe Islands", gender: "Men" },
  { name: "Víkingur", country: "Faroe Islands", gender: "Men" },
  { name: "FC Hoyvik", country: "Faroe Islands", gender: "Women" },
  { name: "AC Oulu", country: "Finland", gender: "Men" },
  { name: "Ekenäs Idrottsförening", country: "Finland", gender: "Men" },
  { name: "FC Haka", country: "Finland", gender: "Men" },
  { name: "FC Honka Espoo", country: "Finland", gender: "Men" },
  { name: "FC Inter Turku", country: "Finland", gender: "Men" },
  { name: "FC Lahti", country: "Finland", gender: "Men" },
  { name: "HJK Helsinki", country: "Finland", gender: "Men" },
  { name: "IF Gnistan", country: "Finland", gender: "Men" },
  { name: "IFK Mariehamn", country: "Finland", gender: "Men" },
  { name: "Ilves Tampere", country: "Finland", gender: "Men" },
  { name: "KuPS Kuopio", country: "Finland", gender: "Men" },
  { name: "SJK Seinäjoki", country: "Finland", gender: "Men" },
  { name: "VPS Vaasa", country: "Finland", gender: "Men" },
  { name: "AJ Auxerre", country: "France", gender: "Men" },
  { name: "Angers SCO", country: "France", gender: "Men" },
  { name: "AS Monaco FC", country: "France", gender: "Men" },
  { name: "AS Saint-Étienne", country: "France", gender: "Men" },
  { name: "Clermont Foot 63", country: "France", gender: "Men" },
  { name: "ESTAC Troyes", country: "France", gender: "Men" },
  { name: "FC Girondins de Bordeaux", country: "France", gender: "Men" },
  { name: "FC Lorient", country: "France", gender: "Men" },
  { name: "FC Metz", country: "France", gender: "Men" },
  { name: "FC Nantes", country: "France", gender: "Men" },
  { name: "LOSC Lille", country: "France", gender: "Men" },
  { name: "Montpellier Hérault SC", country: "France", gender: "Men" },
  { name: "OGC Nice", country: "France", gender: "Men" },
  { name: "Olympique de Marseille", country: "France", gender: "Men" },
  { name: "Olympique Lyonnais", country: "France", gender: "Men" },
  { name: "Paris Saint-Germain", country: "France", gender: "Men" },
  { name: "Racing Club de Strasbourg", country: "France", gender: "Men" },
  { name: "RC Lens", country: "France", gender: "Men" },
  { name: "Stade Brestois 29", country: "France", gender: "Men" },
  { name: "Stade de Reims", country: "France", gender: "Men" },
  { name: "Stade Rennais FC", country: "France", gender: "Men" },
  { name: "Toulouse FC", country: "France", gender: "Men" },
  { name: "Dijon FCO", country: "France", gender: "Women" },
  { name: "En Avant de Guingamp", country: "France", gender: "Women" },
  { name: "Fleury 91 Féminines", country: "France", gender: "Women" },
  { name: "Paris FC", country: "France", gender: "Women" },
  { name: "FC Chikhura Sachkhere", country: "Georgia", gender: "Men" },
  { name: "FC Dila Gori", country: "Georgia", gender: "Men" },
  { name: "FC Dinamo Batoumi", country: "Georgia", gender: "Men" },
  { name: "FC Dinamo Tbilisi", country: "Georgia", gender: "Men" },
  { name: "FC Gagra", country: "Georgia", gender: "Men" },
  { name: "FC Iberia 1999", country: "Georgia", gender: "Men" },
  { name: "FC Kakheti Telavi", country: "Georgia", gender: "Men" },
  { name: "FC Samtredia", country: "Georgia", gender: "Men" },
  { name: "FC Torpedo Kutaisi", country: "Georgia", gender: "Men" },
  { name: "FC Tskaltubo Samgurali", country: "Georgia", gender: "Men" },
  { name: "Kvartali FC", country: "Georgia", gender: "Women" },
  { name: "Lanchkhuti", country: "Georgia", gender: "Women" },
  { name: "WFC NIKE-LUSSO", country: "Georgia", gender: "Women" },
  { name: "1. FC Heidenheim 1846", country: "Germany", gender: "Men" },
  { name: "1. FC Köln", country: "Germany", gender: "Men" },
  { name: "1. FC Nürnberg", country: "Germany", gender: "Men" },
  { name: "1. FC Union Berlin", country: "Germany", gender: "Men" },
  { name: "1. FSV Mainz 05", country: "Germany", gender: "Men" },
  { name: "Bayer 04 Leverkusen", country: "Germany", gender: "Men" },
  { name: "Borussia Dortmund", country: "Germany", gender: "Men" },
  { name: "Borussia VfL 1900 Mönchengladbach", country: "Germany", gender: "Men" },
  { name: "Eintracht Frankfurt", country: "Germany", gender: "Men" },
  { name: "FC Augsburg", country: "Germany", gender: "Men" },
  { name: "FC Bayern München", country: "Germany", gender: "Men" },
  { name: "FC Schalke 04", country: "Germany", gender: "Men" },
  { name: "Hamburger SV", country: "Germany", gender: "Men" },
  { name: "Hertha BSC Berlin", country: "Germany", gender: "Men" },
  { name: "RB Leipzig", country: "Germany", gender: "Men" },
  { name: "SC Freiburg", country: "Germany", gender: "Men" },
  { name: "SV Darmstadt 98", country: "Germany", gender: "Men" },
  { name: "SV Werder Bremen", country: "Germany", gender: "Men" },
  { name: "VfB Stuttgart", country: "Germany", gender: "Men" },
  { name: "VfL Bochum 1848", country: "Germany", gender: "Men" },
  { name: "SGS Essen", country: "Germany", gender: "Women" },
  { name: "TSG 1899 Hoffenheim", country: "Germany", gender: "Women" },
  { name: "VfL Wolfsburg", country: "Germany", gender: "Women" },
  { name: "College 1975 FC", country: "Gibraltar", gender: "Men" },
  { name: "Europa FC", country: "Gibraltar", gender: "Men" },
  { name: "Europa Point FC", country: "Gibraltar", gender: "Men" },
  { name: "FC Hound Dogs", country: "Gibraltar", gender: "Men" },
  { name: "FC Magpies", country: "Gibraltar", gender: "Men" },
  { name: "Glacis United FC", country: "Gibraltar", gender: "Men" },
  { name: "Lincoln Red Imps FC", country: "Gibraltar", gender: "Men" },
  { name: "Lions Gibraltar FC", country: "Gibraltar", gender: "Men" },
  { name: "Lynx FC", country: "Gibraltar", gender: "Men" },
  { name: "Manchester 1962 FC", country: "Gibraltar", gender: "Men" },
  { name: "Mons Calpe SC", country: "Gibraltar", gender: "Men" },
  { name: "St Joseph's FC", country: "Gibraltar", gender: "Men" },
  { name: "Gibraltar Wave FC", country: "Gibraltar", gender: "Women" },
  { name: "Hercules FC", country: "Gibraltar", gender: "Women" },
  { name: "AEK Athens FC", country: "Greece", gender: "Men" },
  { name: "Aris FC", country: "Greece", gender: "Men" },
  { name: "Asteras Tripolis FC", country: "Greece", gender: "Men" },
  { name: "Athens Kallithea F.C.", country: "Greece", gender: "Men" },
  { name: "Atromitos FC", country: "Greece", gender: "Men" },
  { name: "Kifisia FC", country: "Greece", gender: "Men" },
  { name: "Levadiakos F.C.", country: "Greece", gender: "Men" },
  { name: "OFI Crete FC", country: "Greece", gender: "Men" },
  { name: "Olympiacos FC", country: "Greece", gender: "Men" },
  { name: "Panathinaikos FC", country: "Greece", gender: "Men" },
  { name: "Panetolikos FC", country: "Greece", gender: "Men" },
  { name: "Panserraikos FC", country: "Greece", gender: "Men" },
  { name: "PAOK FC", country: "Greece", gender: "Men" },
  { name: "PAS Giannina FC", country: "Greece", gender: "Men" },
  { name: "PAS Lamia", country: "Greece", gender: "Men" },
  { name: "Volos NFC", country: "Greece", gender: "Men" },
  { name: "AS Olimpiada Imittou", country: "Greece", gender: "Women" },
  { name: "Larissa Women", country: "Greece", gender: "Women" },
  { name: "Nees Atromitou", country: "Greece", gender: "Women" },
  { name: "Contoso Football Club", country: "Hungary", gender: "Men" },
  { name: "Budapest Honvéd FC", country: "Hungary", gender: "Men" },
  { name: "Debreceni VSC", country: "Hungary", gender: "Men" },
  { name: "Fehérvár FC", country: "Hungary", gender: "Men" },
  { name: "Ferencvárosi TC", country: "Hungary", gender: "Men" },
  { name: "Gyori ETO FC", country: "Hungary", gender: "Men" },
  { name: "MTK Budapest FC", country: "Hungary", gender: "Men" },
  { name: "Puskás Akadémia FC", country: "Hungary", gender: "Men" },
  { name: "Újpest FC", country: "Hungary", gender: "Men" },
  { name: "ZTE FC", country: "Hungary", gender: "Men" },
  { name: "Kisvárda FC", country: "Hungary", gender: "Women" },
  { name: "Breidablik", country: "Iceland", gender: "Men" },
  { name: "FH Hafnarfjördur", country: "Iceland", gender: "Men" },
  { name: "Fram Reykjavik FC", country: "Iceland", gender: "Men" },
  { name: "Fylkir", country: "Iceland", gender: "Men" },
  { name: "HK Kopavogs", country: "Iceland", gender: "Men" },
  { name: "ÍA Akranes", country: "Iceland", gender: "Men" },
  { name: "IBV Íþróttabandalag Vestmannaeyja", country: "Iceland", gender: "Men" },
  { name: "KA Akureyri", country: "Iceland", gender: "Men" },
  { name: "Keflavík", country: "Iceland", gender: "Men" },
  { name: "KR Reykjavík", country: "Iceland", gender: "Men" },
  { name: "Stjarnan", country: "Iceland", gender: "Men" },
  { name: "Ungmennafélagið Afturelding", country: "Iceland", gender: "Men" },
  { name: "Valur", country: "Iceland", gender: "Men" },
  { name: "Vestri", country: "Iceland", gender: "Men" },
  { name: "Víkingur Reykjavik", country: "Iceland", gender: "Men" },
  { name: "Thór/KA", country: "Iceland", gender: "Women" },
  { name: "Thróttur Reykjavík", country: "Iceland", gender: "Women" },
  { name: "Cork City FC", country: "Ireland", gender: "Men" },
  { name: "Derry City FC", country: "Ireland", gender: "Men" },
  { name: "Drogheda United FC", country: "Ireland", gender: "Men" },
  { name: "Dundalk FC", country: "Ireland", gender: "Men" },
  { name: "Galway United FC", country: "Ireland", gender: "Men" },
  { name: "Saint Patrick's Athletic FC", country: "Ireland", gender: "Men" },
  { name: "Shamrock Rovers FC", country: "Ireland", gender: "Men" },
  { name: "Shelbourne FC", country: "Ireland", gender: "Men" },
  { name: "Sligo Rovers FC", country: "Ireland", gender: "Men" },
  { name: "Waterford FC", country: "Ireland", gender: "Men" },
  { name: "DLR Waves", country: "Ireland", gender: "Women" },
  { name: "Peamount United FC", country: "Ireland", gender: "Women" },
  { name: "Beitar Jerusalem FC", country: "Israel", gender: "Men" },
  { name: "Bnei Sakhnin FC", country: "Israel", gender: "Men" },
  { name: "Bnei Yehuda Tel-Aviv FC", country: "Israel", gender: "Men" },
  { name: "FC Ashdod", country: "Israel", gender: "Men" },
  { name: "Hapoel Beer-Sheva FC", country: "Israel", gender: "Men" },
  { name: "Hapoel Hadera", country: "Israel", gender: "Men" },
  { name: "Hapoel Haifa FC", country: "Israel", gender: "Men" },
  { name: "Hapoel Jerusalem FC", country: "Israel", gender: "Men" },
  { name: "Hapoel Petah Tikva FC", country: "Israel", gender: "Men" },
  { name: "Hapoel Tel-Aviv FC", country: "Israel", gender: "Men" },
  { name: "Ironi Tiberias FC", country: "Israel", gender: "Men" },
  { name: "Maccabi Bnei Reineh", country: "Israel", gender: "Men" },
  { name: "Maccabi Haifa FC", country: "Israel", gender: "Men" },
  { name: "Maccabi Petah Tikva FC", country: "Israel", gender: "Men" },
  { name: "Maccabi Tel-Aviv FC", country: "Israel", gender: "Men" },
  { name: "ASA Tel-Aviv University SC", country: "Israel", gender: "Women" },
  { name: "Bnot Netanya FC", country: "Israel", gender: "Women" },
  { name: "Kiryat Gat W.F.C.", country: "Israel", gender: "Women" },
  { name: "Maccabi Kishronot Hadera", country: "Israel", gender: "Women" },
  { name: "Raanana Women's Soccer FC", country: "Israel", gender: "Women" },
  { name: "WFC Ramat Hasharon", country: "Israel", gender: "Women" },
  { name: "AC Milan", country: "Italy", gender: "Men" },
  { name: "AS Roma", country: "Italy", gender: "Men" },
  { name: "Atalanta BC", country: "Italy", gender: "Men" },
  { name: "Bologna FC", country: "Italy", gender: "Men" },
  { name: "Cagliari Calcio", country: "Italy", gender: "Men" },
  { name: "Como 1907", country: "Italy", gender: "Men" },
  { name: "Empoli FC", country: "Italy", gender: "Men" },
  { name: "FC Internazionale Milano", country: "Italy", gender: "Men" },
  { name: "Frosinone Calcio", country: "Italy", gender: "Men" },
  { name: "Genoa CFC", country: "Italy", gender: "Men" },
  { name: "Hellas Verona FC", country: "Italy", gender: "Men" },
  { name: "Juventus FC", country: "Italy", gender: "Men" },
  { name: "Monza", country: "Italy", gender: "Men" },
  { name: "Parma Calcio 1913", country: "Italy", gender: "Men" },
  { name: "Pisa SC", country: "Italy", gender: "Men" },
  { name: "SS Lazio", country: "Italy", gender: "Men" },
  { name: "SSC Napoli", country: "Italy", gender: "Men" },
  { name: "Torino FC", country: "Italy", gender: "Men" },
  { name: "Udinese Calcio", country: "Italy", gender: "Men" },
  { name: "US Cremonese", country: "Italy", gender: "Men" },
  { name: "US Lecce", country: "Italy", gender: "Men" },
  { name: "US Salernitana 1919", country: "Italy", gender: "Men" },
  { name: "US Sassuolo Calcio", country: "Italy", gender: "Men" },
  { name: "Venezia FC", country: "Italy", gender: "Men" },
  { name: "ACF Fiorentina", country: "Italy", gender: "Women" },
  { name: "FC Como Women", country: "Italy", gender: "Women" },
  { name: "UC Sampdoria", country: "Italy", gender: "Women" },
  { name: "FC Aktobe", country: "Kazakhstan", gender: "Men" },
  { name: "FC Akzhayik", country: "Kazakhstan", gender: "Men" },
  { name: "FC Astana", country: "Kazakhstan", gender: "Men" },
  { name: "FC Kairat Almaty", country: "Kazakhstan", gender: "Men" },
  { name: "FC Shakhter Karagandy", country: "Kazakhstan", gender: "Men" },
  { name: "FK Yelimay Semey", country: "Kazakhstan", gender: "Men" },
  { name: "FC Okzhetpes Kokshetau", country: "Kazakhstan", gender: "Women" },
  { name: "FC Ordabasy Shymkent", country: "Kazakhstan", gender: "Women" },
  { name: "WFC BIIK-Shymkent", country: "Kazakhstan", gender: "Women" },
  { name: "FC Ballkani", country: "Kosovo", gender: "Men" },
  { name: "FC Drita", country: "Kosovo", gender: "Men" },
  { name: "FC Ferizaj", country: "Kosovo", gender: "Men" },
  { name: "FC Malisheva", country: "Kosovo", gender: "Men" },
  { name: "FC Prishtina", country: "Kosovo", gender: "Men" },
  { name: "FC Suhareka", country: "Kosovo", gender: "Men" },
  { name: "KF Dukagjini", country: "Kosovo", gender: "Men" },
  { name: "KF Feronikeli", country: "Kosovo", gender: "Men" },
  { name: "KF Liria", country: "Kosovo", gender: "Men" },
  { name: "KF Llapi 1932", country: "Kosovo", gender: "Men" },
  { name: "KF Prishtina e Re", country: "Kosovo", gender: "Men" },
  { name: "SC Gjilani", country: "Kosovo", gender: "Men" },
  { name: "KFF 16 Qershori", country: "Kosovo", gender: "Women" },
  { name: "KFF Bazeli 2015", country: "Kosovo", gender: "Women" },
  { name: "KFF Llapi Women", country: "Kosovo", gender: "Women" },
  { name: "KFF Mitrovica", country: "Kosovo", gender: "Women" },
  { name: "KFF Presingu", country: "Kosovo", gender: "Women" },
  { name: "KFF Ulpiana 1992", country: "Kosovo", gender: "Women" },
  { name: "KFV Prishtina", country: "Kosovo", gender: "Women" },
  { name: "WFC Hajvalia", country: "Kosovo", gender: "Women" },
  { name: "FK Auda", country: "Latvia", gender: "Men" },
  { name: "FK Liepāja", country: "Latvia", gender: "Men" },
  { name: "Riga FC", country: "Latvia", gender: "Men" },
  { name: "Valmiera FC", country: "Latvia", gender: "Men" },
  { name: "FC Vaduz", country: "Liechtenstein", gender: "Men" },
  { name: "Džiugas Telsiai", country: "Lithuania", gender: "Men" },
  { name: "FK Dainava", country: "Lithuania", gender: "Men" },
  { name: "FK Kauno Žalgiris", country: "Lithuania", gender: "Men" },
  { name: "FK Panevėžys", country: "Lithuania", gender: "Men" },
  { name: "FK Riteriai", country: "Lithuania", gender: "Men" },
  { name: "FK Sūduva", country: "Lithuania", gender: "Men" },
  { name: "FK Žalgiris Vilnius", country: "Lithuania", gender: "Men" },
  { name: "FC Gintra", country: "Lithuania", gender: "Women" },
  { name: "FK Utenis Utena", country: "Lithuania", gender: "Women" },
  { name: "AS Jeunesse Esch", country: "Luxembourg", gender: "Men" },
  { name: "Atert Bissen", country: "Luxembourg", gender: "Men" },
  { name: "CS Fola Esch", country: "Luxembourg", gender: "Men" },
  { name: "F91 Diddeleng", country: "Luxembourg", gender: "Men" },
  { name: "FC Differdange 03", country: "Luxembourg", gender: "Men" },
  { name: "FC Jeunesse Canach", country: "Luxembourg", gender: "Men" },
  { name: "FC Mamer 32", country: "Luxembourg", gender: "Men" },
  { name: "FC Mondercange", country: "Luxembourg", gender: "Men" },
  { name: "FC Progrès Niederkorn", country: "Luxembourg", gender: "Men" },
  { name: "FC Rodange 91", country: "Luxembourg", gender: "Men" },
  { name: "FC Schifflange 95", country: "Luxembourg", gender: "Men" },
  { name: "FC Swift Hesperange", country: "Luxembourg", gender: "Men" },
  { name: "FC UNA Strassen", country: "Luxembourg", gender: "Men" },
  { name: "FC Victoria Rosport", country: "Luxembourg", gender: "Men" },
  { name: "FC Wiltz 71", country: "Luxembourg", gender: "Men" },
  { name: "Marisca Mersch", country: "Luxembourg", gender: "Men" },
  { name: "Racing FC Union Luxembourg", country: "Luxembourg", gender: "Men" },
  { name: "SC Bettembourg", country: "Luxembourg", gender: "Men" },
  { name: "UN Käerjéng 97", country: "Luxembourg", gender: "Men" },
  { name: "Union Titus Pétange", country: "Luxembourg", gender: "Men" },
  { name: "US Hostert", country: "Luxembourg", gender: "Men" },
  { name: "US Mondorf-les-Bains", country: "Luxembourg", gender: "Men" },
  { name: "Entente Hosingen Norden Women", country: "Luxembourg", gender: "Women" },
  { name: "Entente Wormeldange WMG", country: "Luxembourg", gender: "Women" },
  { name: "FC Jeunesse Jonglënster", country: "Luxembourg", gender: "Women" },
  { name: "Balzan FC", country: "Malta", gender: "Men" },
  { name: "Birkirkara FC", country: "Malta", gender: "Men" },
  { name: "Floriana FC", country: "Malta", gender: "Men" },
  { name: "Gzira United FC", country: "Malta", gender: "Men" },
  { name: "Hamrun Spartans FC", country: "Malta", gender: "Men" },
  { name: "Hibernians FC", country: "Malta", gender: "Men" },
  { name: "Mosta FC", country: "Malta", gender: "Men" },
  { name: "Sliema Wanderers FC", country: "Malta", gender: "Men" },
  { name: "Zabbar St Patrick FC", country: "Malta", gender: "Men" },
  { name: "Swieqi United", country: "Malta", gender: "Women" },
  { name: "Valletta FC", country: "Malta", gender: "Women" },
  { name: "CS Dacia-Buiucani", country: "Moldova", gender: "Men" },
  { name: "FC Balti", country: "Moldova", gender: "Men" },
  { name: "FC Floresti", country: "Moldova", gender: "Men" },
  { name: "FC Milsami Orhei", country: "Moldova", gender: "Men" },
  { name: "FC Petrocub-Hincesti", country: "Moldova", gender: "Men" },
  { name: "FC Sheriff Tiraspol", country: "Moldova", gender: "Men" },
  { name: "FC Zimbru Chisinau", country: "Moldova", gender: "Men" },
  { name: "FC Mladost Donja Gorica", country: "Montenegro", gender: "Men" },
  { name: "FK Budućnost Podgorica", country: "Montenegro", gender: "Men" },
  { name: "FK Dečić", country: "Montenegro", gender: "Men" },
  { name: "FK Jedinstvo Bijelo Polje", country: "Montenegro", gender: "Men" },
  { name: "FK Jezero", country: "Montenegro", gender: "Men" },
  { name: "FK Mornar Bar", country: "Montenegro", gender: "Men" },
  { name: "FK Otrant Olympic", country: "Montenegro", gender: "Men" },
  { name: "FK Rudar Pljevlja", country: "Montenegro", gender: "Men" },
  { name: "FK Sutjeska", country: "Montenegro", gender: "Men" },
  { name: "FK Zeta", country: "Montenegro", gender: "Men" },
  { name: "OFK Petrovac", country: "Montenegro", gender: "Men" },
  { name: "OFK Titograd", country: "Montenegro", gender: "Men" },
  { name: "FK Breznica Pljevlja", country: "Montenegro", gender: "Women" },
  { name: "ŽFK Zora", country: "Montenegro", gender: "Women" },
  { name: "AFC Ajax", country: "Netherlands", gender: "Men" },
  { name: "Almere City FC", country: "Netherlands", gender: "Men" },
  { name: "AZ Alkmaar", country: "Netherlands", gender: "Men" },
  { name: "Excelsior Rotterdam", country: "Netherlands", gender: "Men" },
  { name: "FC Utrecht", country: "Netherlands", gender: "Men" },
  { name: "Feyenoord", country: "Netherlands", gender: "Men" },
  { name: "Go Ahead Eagles", country: "Netherlands", gender: "Men" },
  { name: "Heracles Almelo", country: "Netherlands", gender: "Men" },
  { name: "NEC Nijmegen", country: "Netherlands", gender: "Men" },
  { name: "PEC Zwolle", country: "Netherlands", gender: "Men" },
  { name: "PSV Eindhoven", country: "Netherlands", gender: "Men" },
  { name: "RKC Waalwijk", country: "Netherlands", gender: "Men" },
  { name: "SC Fortuna Sittard", country: "Netherlands", gender: "Men" },
  { name: "SC Heerenveen", country: "Netherlands", gender: "Men" },
  { name: "SC Telstar VVNH", country: "Netherlands", gender: "Men" },
  { name: "Sparta Rotterdam", country: "Netherlands", gender: "Men" },
  { name: "FC Twente", country: "Netherlands", gender: "Women" },
  { name: "Hera United", country: "Netherlands", gender: "Women" },
  { name: "FC AP Brera Strumica", country: "North Macedonia", gender: "Men" },
  { name: "FC Bashkimi 1947 Kumanovo", country: "North Macedonia", gender: "Men" },
  { name: "FC Shkupi 1927", country: "North Macedonia", gender: "Men" },
  { name: "FC Struga", country: "North Macedonia", gender: "Men" },
  { name: "FK Aresimi-1973 AD", country: "North Macedonia", gender: "Men" },
  { name: "FK Bregalnica Stip", country: "North Macedonia", gender: "Men" },
  { name: "FK Gostivar", country: "North Macedonia", gender: "Men" },
  { name: "FK Makedonija GP Skopje", country: "North Macedonia", gender: "Men" },
  { name: "FK Rabotnicki", country: "North Macedonia", gender: "Men" },
  { name: "FK Sileks Kratovo", country: "North Macedonia", gender: "Men" },
  { name: "FK Tikvesh", country: "North Macedonia", gender: "Men" },
  { name: "FK Vardar", country: "North Macedonia", gender: "Men" },
  { name: "FK Voska Sport", country: "North Macedonia", gender: "Men" },
  { name: "Football Club Pelister Bitola", country: "North Macedonia", gender: "Men" },
  { name: "KF Shkëndija", country: "North Macedonia", gender: "Men" },
  { name: "Kamenica Sasa", country: "North Macedonia", gender: "Women" },
  { name: "ZFK Cevitana Prilep", country: "North Macedonia", gender: "Women" },
  { name: "ZFK Istatov", country: "North Macedonia", gender: "Women" },
  { name: "ŽFK Ljuboten", country: "North Macedonia", gender: "Women" },
  { name: "ZFK Recica", country: "North Macedonia", gender: "Women" },
  { name: "ZFK Tiverija", country: "North Macedonia", gender: "Women" },
  { name: "Ballymena United FC", country: "Northern Ireland", gender: "Men" },
  { name: "Bangor FC", country: "Northern Ireland", gender: "Men" },
  { name: "Cliftonville FC", country: "Northern Ireland", gender: "Men" },
  { name: "Coleraine FC", country: "Northern Ireland", gender: "Men" },
  { name: "Crusaders FC", country: "Northern Ireland", gender: "Men" },
  { name: "Dungannon Swifts FC", country: "Northern Ireland", gender: "Men" },
  { name: "Glenavon FC", country: "Northern Ireland", gender: "Men" },
  { name: "Glentoran FC", country: "Northern Ireland", gender: "Men" },
  { name: "Larne FC", country: "Northern Ireland", gender: "Men" },
  { name: "Linfield FC", country: "Northern Ireland", gender: "Men" },
  { name: "Bryne FK", country: "Norway", gender: "Men" },
  { name: "FK Bodø/Glimt", country: "Norway", gender: "Men" },
  { name: "FK Haugesund", country: "Norway", gender: "Men" },
  { name: "Fredrikstad FK", country: "Norway", gender: "Men" },
  { name: "Kristiansund BK", country: "Norway", gender: "Men" },
  { name: "Molde FK", country: "Norway", gender: "Men" },
  { name: "Odds BK", country: "Norway", gender: "Men" },
  { name: "Rosenborg BK", country: "Norway", gender: "Men" },
  { name: "Sandefjord Fotball", country: "Norway", gender: "Men" },
  { name: "SK Brann", country: "Norway", gender: "Men" },
  { name: "Stabæk Fotball", country: "Norway", gender: "Men" },
  { name: "Strømsgodset", country: "Norway", gender: "Men" },
  { name: "Tromsø IL", country: "Norway", gender: "Men" },
  { name: "Viking FK", country: "Norway", gender: "Men" },
  { name: "Kolbotn", country: "Norway", gender: "Women" },
  { name: "Lillestrøm SK", country: "Norway", gender: "Women" },
  { name: "Røa IL", country: "Norway", gender: "Women" },
  { name: "Vålerenga Fotball", country: "Norway", gender: "Women" },
  { name: "Jagiellonia Białystok", country: "Poland", gender: "Men" },
  { name: "KKS Lech Poznań", country: "Poland", gender: "Men" },
  { name: "Korona Kielce", country: "Poland", gender: "Men" },
  { name: "KS Cracovia SA", country: "Poland", gender: "Men" },
  { name: "KS Lechia Gdańsk", country: "Poland", gender: "Men" },
  { name: "Legia Warszawa", country: "Poland", gender: "Men" },
  { name: "MKS Pogoń Szczecin", country: "Poland", gender: "Men" },
  { name: "MKS Puszcza Niepolomice", country: "Poland", gender: "Men" },
  { name: "Radomiak Radom", country: "Poland", gender: "Men" },
  { name: "Raków Czestochowa", country: "Poland", gender: "Men" },
  { name: "RTS Widzew Łódź", country: "Poland", gender: "Men" },
  { name: "Warta Poznań", country: "Poland", gender: "Men" },
  { name: "Wisła Kraków", country: "Poland", gender: "Men" },
  { name: "WKS Śląsk Wrocław", country: "Poland", gender: "Men" },
  { name: "GKS Górnik Leczna", country: "Poland", gender: "Women" },
  { name: "AVS Futebol SAD", country: "Portugal", gender: "Men" },
  { name: "Boavista FC", country: "Portugal", gender: "Men" },
  { name: "Casa Pia AC", country: "Portugal", gender: "Men" },
  { name: "CF Estrela da Amadora", country: "Portugal", gender: "Men" },
  { name: "CS Marítimo", country: "Portugal", gender: "Men" },
  { name: "Estoril Praia", country: "Portugal", gender: "Men" },
  { name: "FC Famalicao", country: "Portugal", gender: "Men" },
  { name: "FC Porto", country: "Portugal", gender: "Men" },
  { name: "FC Vizela", country: "Portugal", gender: "Men" },
  { name: "Gil Vicente FC", country: "Portugal", gender: "Men" },
  { name: "Rio Ave FC", country: "Portugal", gender: "Men" },
  { name: "SC Braga", country: "Portugal", gender: "Men" },
  { name: "SC Farense", country: "Portugal", gender: "Men" },
  { name: "SL Benfica", country: "Portugal", gender: "Men" },
  { name: "Sporting Clube de Portugal", country: "Portugal", gender: "Men" },
  { name: "Vitória SC", country: "Portugal", gender: "Men" },
  { name: "SCU Torreense", country: "Portugal", gender: "Women" },
  { name: "Valadares Gaia FC", country: "Portugal", gender: "Women" },
  { name: "CFR 1907 Cluj", country: "Romania", gender: "Men" },
  { name: "CSM Politehnica Iași", country: "Romania", gender: "Men" },
  { name: "FC Botosani", country: "Romania", gender: "Men" },
  { name: "FC Dinamo Bucureşti", country: "Romania", gender: "Men" },
  { name: "FC Otelul Galati", country: "Romania", gender: "Men" },
  { name: "FC Petrolul Ploiesti", country: "Romania", gender: "Men" },
  { name: "FC Rapid București", country: "Romania", gender: "Men" },
  { name: "FC Universitatea Cluj", country: "Romania", gender: "Men" },
  { name: "FC Voluntari", country: "Romania", gender: "Men" },
  { name: "FCSB", country: "Romania", gender: "Men" },
  { name: "FCV Farul Constanţa", country: "Romania", gender: "Men" },
  { name: "AFK Csikszereda Miercurea Ciuc", country: "Romania", gender: "Women" },
  { name: "CS Atletic Olimpia Gherla", country: "Romania", gender: "Women" },
  { name: "AC Juvenes-Dogana", country: "San Marino", gender: "Men" },
  { name: "AC Libertas", country: "San Marino", gender: "Men" },
  { name: "FC Fiorentino", country: "San Marino", gender: "Men" },
  { name: "La Fiorita 1967", country: "San Marino", gender: "Men" },
  { name: "SC Faetano", country: "San Marino", gender: "Men" },
  { name: "SP Cailungo", country: "San Marino", gender: "Men" },
  { name: "SP Tre Fiori", country: "San Marino", gender: "Men" },
  { name: "SP Tre Penne", country: "San Marino", gender: "Men" },
  { name: "SS Cosmos", country: "San Marino", gender: "Men" },
  { name: "SS Folgore", country: "San Marino", gender: "Men" },
  { name: "SS Murata", country: "San Marino", gender: "Men" },
  { name: "SS San Giovanni", country: "San Marino", gender: "Men" },
  { name: "SS Virtus", country: "San Marino", gender: "Men" },
  { name: "Aberdeen FC", country: "Scotland", gender: "Men" },
  { name: "Celtic FC", country: "Scotland", gender: "Men" },
  { name: "Dundee FC", country: "Scotland", gender: "Men" },
  { name: "Dundee United", country: "Scotland", gender: "Men" },
  { name: "Falkirk Football Club", country: "Scotland", gender: "Men" },
  { name: "Heart of Midlothian FC", country: "Scotland", gender: "Men" },
  { name: "Hibernian FC", country: "Scotland", gender: "Men" },
  { name: "Kilmarnock FC", country: "Scotland", gender: "Men" },
  { name: "Livingston FC", country: "Scotland", gender: "Men" },
  { name: "Motherwell FC", country: "Scotland", gender: "Men" },
  { name: "Rangers FC", country: "Scotland", gender: "Men" },
  { name: "Ross County FC", country: "Scotland", gender: "Men" },
  { name: "Spartans FC", country: "Scotland", gender: "Men" },
  { name: "St Johnstone FC", country: "Scotland", gender: "Men" },
  { name: "St Mirren Football Club", country: "Scotland", gender: "Men" },
  { name: "Glasgow City FC", country: "Scotland", gender: "Women" },
  { name: "Hamilton Academical WFC", country: "Scotland", gender: "Women" },
  { name: "Montrose FC Women", country: "Scotland", gender: "Women" },
  { name: "Partick Thistle Women's Football Club", country: "Scotland", gender: "Women" },
  { name: "FK Crvena Zvezda", country: "Serbia", gender: "Men" },
  { name: "FK Čukarički", country: "Serbia", gender: "Men" },
  { name: "FK IMT Beograd", country: "Serbia", gender: "Men" },
  { name: "FK Javor-Matis", country: "Serbia", gender: "Men" },
  { name: "FK Jedinstvo Ub", country: "Serbia", gender: "Men" },
  { name: "FK Mladost Lučani", country: "Serbia", gender: "Men" },
  { name: "FK Novi Pazar", country: "Serbia", gender: "Men" },
  { name: "FK Partizan", country: "Serbia", gender: "Men" },
  { name: "FK Radnički Niš", country: "Serbia", gender: "Men" },
  { name: "FK Radnik Surdulica", country: "Serbia", gender: "Men" },
  { name: "FK Spartak Subotica", country: "Serbia", gender: "Men" },
  { name: "FK Tekstilac Odžaci", country: "Serbia", gender: "Men" },
  { name: "FK Vojvodina", country: "Serbia", gender: "Men" },
  { name: "FK Voždovac", country: "Serbia", gender: "Men" },
  { name: "FK Železničar Pančevo", country: "Serbia", gender: "Men" },
  { name: "OFK Beograd", country: "Serbia", gender: "Men" },
  { name: "TSC Backa Topola", country: "Serbia", gender: "Men" },
  { name: "FK Napredak", country: "Serbia", gender: "Women" },
  { name: "ZFK Crvena Zvezda", country: "Serbia", gender: "Women" },
  { name: "ZFK Masinac Nis", country: "Serbia", gender: "Women" },
  { name: "ŽFK Milutniac 2023 Zemun", country: "Serbia", gender: "Women" },
  { name: "ZFK Sloga Zemun", country: "Serbia", gender: "Women" },
  { name: "ZFK Spartak Subotica", country: "Serbia", gender: "Women" },
  { name: "ŽFK TSC Kanjiža", country: "Serbia", gender: "Women" },
  { name: "AS Trenčín", country: "Slovakia", gender: "Men" },
  { name: "FC DAC 1904 Dunajská Streda", country: "Slovakia", gender: "Men" },
  { name: "FC Spartak Trnava", country: "Slovakia", gender: "Men" },
  { name: "FC ViOn Zlaté Moravce", country: "Slovakia", gender: "Men" },
  { name: "MFK Ružomberok", country: "Slovakia", gender: "Men" },
  { name: "MŠK Žilina", country: "Slovakia", gender: "Men" },
  { name: "ŠK Slovan Bratislava", country: "Slovakia", gender: "Men" },
  { name: "NK Bravo", country: "Slovenia", gender: "Men" },
  { name: "NK Celje", country: "Slovenia", gender: "Men" },
  { name: "NK Domžale", country: "Slovenia", gender: "Men" },
  { name: "NK Maribor", country: "Slovenia", gender: "Men" },
  { name: "NK Nafta 1903", country: "Slovenia", gender: "Men" },
  { name: "NK Olimpija Ljubljana", country: "Slovenia", gender: "Men" },
  { name: "NK Radomlje", country: "Slovenia", gender: "Men" },
  { name: "Rogaska", country: "Slovenia", gender: "Men" },
  { name: "FC Koper", country: "Slovenia", gender: "Women" },
  { name: "NK Aluminij", country: "Slovenia", gender: "Women" },
  { name: "NK Gazon", country: "Slovenia", gender: "Women" },
  { name: "NŠ Mura", country: "Slovenia", gender: "Women" },
  { name: "ZNK Cerklje", country: "Slovenia", gender: "Women" },
  { name: "ZNK Olimpija Ljubljana", country: "Slovenia", gender: "Women" },
  { name: "ZNK Primorje Ajdovscina", country: "Slovenia", gender: "Women" },
  { name: "Athletic Club", country: "Spain", gender: "Men" },
  { name: "Club Atlético de Madrid", country: "Spain", gender: "Men" },
  { name: "FC Barcelona", country: "Spain", gender: "Men" },
  { name: "Getafe CF", country: "Spain", gender: "Men" },
  { name: "Girona FC", country: "Spain", gender: "Men" },
  { name: "RC Celta de Vigo", country: "Spain", gender: "Men" },
  { name: "RCD Espanyol", country: "Spain", gender: "Men" },
  { name: "Real Betis Balompié", country: "Spain", gender: "Men" },
  { name: "Real Sociedad de Fútbol", country: "Spain", gender: "Men" },
  { name: "Real Zaragoza", country: "Spain", gender: "Men" },
  { name: "Sevilla FC", country: "Spain", gender: "Men" },
  { name: "Valencia CF", country: "Spain", gender: "Men" },
  { name: "Villarreal CF", country: "Spain", gender: "Men" },
  { name: "CD Tenerife Femenino", country: "Spain", gender: "Women" },
  { name: "FC Badalona Women", country: "Spain", gender: "Women" },
  { name: "Levante UD", country: "Spain", gender: "Women" },
  { name: "Madrid CFF", country: "Spain", gender: "Women" },
  { name: "Real Club Deportivo de La Coruña", country: "Spain", gender: "Women" },
  { name: "AIK", country: "Sweden", gender: "Men" },
  { name: "Djurgårdens IF", country: "Sweden", gender: "Men" },
  { name: "GAIS", country: "Sweden", gender: "Men" },
  { name: "Hammarby Fotboll", country: "Sweden", gender: "Men" },
  { name: "IF Brommapojkarna", country: "Sweden", gender: "Men" },
  { name: "IF Elfsborg", country: "Sweden", gender: "Men" },
  { name: "IFK Göteborg", country: "Sweden", gender: "Men" },
  { name: "IFK Norrköping", country: "Sweden", gender: "Men" },
  { name: "Malmö FF", country: "Sweden", gender: "Men" },
  { name: "Mjällby AIF", country: "Sweden", gender: "Men" },
  { name: "BK Häcken", country: "Sweden", gender: "Women" },
  { name: "FC Rosengård", country: "Sweden", gender: "Women" },
  { name: "Kristianstads DFF", country: "Sweden", gender: "Women" },
  { name: "Linköpings FC", country: "Sweden", gender: "Women" },
  { name: "Vittsjö GIK", country: "Sweden", gender: "Women" },
  { name: "BSC Young Boys", country: "Switzerland", gender: "Men" },
  { name: "FC Basel 1893", country: "Switzerland", gender: "Men" },
  { name: "FC Lausanne-Sport", country: "Switzerland", gender: "Men" },
  { name: "FC Lugano", country: "Switzerland", gender: "Men" },
  { name: "FC Sion", country: "Switzerland", gender: "Men" },
  { name: "FC St. Gallen 1879", country: "Switzerland", gender: "Men" },
  { name: "FC Stade-Lausanne-Ouchy", country: "Switzerland", gender: "Men" },
  { name: "FC Thun", country: "Switzerland", gender: "Men" },
  { name: "Grasshopper Club Zürich", country: "Switzerland", gender: "Men" },
  { name: "Yverdon Sport FC", country: "Switzerland", gender: "Men" },
  { name: "FC Aarau Frauen", country: "Switzerland", gender: "Women" },
  { name: "FC Luzern", country: "Switzerland", gender: "Women" },
  { name: "FC Rapperswil-Jona", country: "Switzerland", gender: "Women" },
  { name: "FC Zürich", country: "Switzerland", gender: "Women" },
  { name: "Frauenteam Thun Berner-Oberland", country: "Switzerland", gender: "Women" },
  { name: "Servette FC", country: "Switzerland", gender: "Women" },
  { name: "Adana Demirspor AS", country: "Turkey", gender: "Men" },
  { name: "Alanyaspor", country: "Turkey", gender: "Men" },
  { name: "Antalyaspor", country: "Turkey", gender: "Men" },
  { name: "Beşiktaş JK", country: "Turkey", gender: "Men" },
  { name: "Bodrum FK", country: "Turkey", gender: "Men" },
  { name: "Eyüpspor", country: "Turkey", gender: "Men" },
  { name: "Fatih Karagümrük AŞ", country: "Turkey", gender: "Men" },
  { name: "Fenerbahçe SK", country: "Turkey", gender: "Men" },
  { name: "Galatasaray AŞ", country: "Turkey", gender: "Men" },
  { name: "Gaziantep Futbol Kulübü AŞ", country: "Turkey", gender: "Men" },
  { name: "Göztepe SK", country: "Turkey", gender: "Men" },
  { name: "Hatayspor", country: "Turkey", gender: "Men" },
  { name: "İstanbul Başakşehir", country: "Turkey", gender: "Men" },
  { name: "Kasımpaşa SK", country: "Turkey", gender: "Men" },
  { name: "Kayserispor", country: "Turkey", gender: "Men" },
  { name: "Konyaspor", country: "Turkey", gender: "Men" },
  { name: "MKE Ankaragücü", country: "Turkey", gender: "Men" },
  { name: "Pendikspor", country: "Turkey", gender: "Men" },
  { name: "Rizespor", country: "Turkey", gender: "Men" },
  { name: "Samsunspor", country: "Turkey", gender: "Men" },
  { name: "Sivasspor", country: "Turkey", gender: "Men" },
  { name: "Trabzonspor AŞ", country: "Turkey", gender: "Men" },
  { name: "ABB Fomget SK", country: "Turkey", gender: "Women" },
  { name: "ALG Spor Kulübü", country: "Turkey", gender: "Women" },
  { name: "Amed Sportif Faaliyeteler Kulubu", country: "Turkey", gender: "Women" },
  { name: "Beylerbeyispor", country: "Turkey", gender: "Women" },
  { name: "Fatih Vatan Spor Kulübü", country: "Turkey", gender: "Women" },
  { name: "FC Chornomorets Odesa", country: "Ukraine", gender: "Men" },
  { name: "FC Dynamo Kyiv", country: "Ukraine", gender: "Men" },
  { name: "FC Karpaty Lviv", country: "Ukraine", gender: "Men" },
  { name: "FC Kryvbas Kryvyi Rih", country: "Ukraine", gender: "Men" },
  { name: "FC Metalist 1925 Kharkiv", country: "Ukraine", gender: "Men" },
  { name: "FC Oleksandriya", country: "Ukraine", gender: "Men" },
  { name: "FC Shakhtar Donetsk", country: "Ukraine", gender: "Men" },
  { name: "FC Zorya Luhansk", country: "Ukraine", gender: "Men" },
  { name: "NK Veres Rivne", country: "Ukraine", gender: "Men" },
  { name: "Polissya Zhytomyr", country: "Ukraine", gender: "Men" },
  { name: "FC Vorskla Poltava", country: "Ukraine", gender: "Women" },
  { name: "Ipswich Town Football Club", country: "England", gender: "Men" },
  { name: "Cardiff Metropolitan University FC", country: "Wales", gender: "Men" },
  { name: "Connah's Quay Nomads FC", country: "Wales", gender: "Men" },
  { name: "Llanelli Town AFC", country: "Wales", gender: "Men" },
  { name: "Penybont FC", country: "Wales", gender: "Men" },
  { name: "The New Saints FC", country: "Wales", gender: "Men" },
  { name: "Cardiff City FC", country: "Wales", gender: "Women" },
  { name: "Wrexham AFC", country: "Wales", gender: "Women" },
];

export const EFC_CLUB_NAMES: string[] = EFC_CLUBS.map((c) => c.name);

// Known crest URLs (football-data.org). Others fall back to a generated SVG.
export const KNOWN_CLUB_LOGOS: Record<string, string> = {
  "AFC Ajax": "https://crests.football-data.org/678.png",
  "AC Milan": "https://crests.football-data.org/98.png",
  "FC Internazionale Milano": "https://crests.football-data.org/108.png",
  "SL Benfica": "https://crests.football-data.org/1903.png",
  "FC Porto": "https://crests.football-data.org/503.png",
  "Arsenal FC": "https://crests.football-data.org/57.png",
  "Chelsea FC": "https://crests.football-data.org/61.png",
  "Manchester City FC": "https://crests.football-data.org/65.png",
  "FC Bayern München": "https://crests.football-data.org/5.png",
  "Liverpool FC": "https://crests.football-data.org/64.png",
  "Juventus FC": "https://crests.football-data.org/109.png",
  "AC Sparta Praha": "https://crests.football-data.org/747.png",
  "Sevilla FC": "https://crests.football-data.org/559.png",
  "RB Leipzig": "https://crests.football-data.org/721.png",
  "Celtic FC": "https://crests.football-data.org/732.png",
  "Aberdeen FC": "https://crests.football-data.org/1002.png",
  "Paris Saint-Germain": "https://crests.football-data.org/524.png",
  "Borussia Dortmund": "https://crests.football-data.org/4.png",
  "Atlético de Madrid": "https://crests.football-data.org/78.png",
};

// ---- Normalization ---------------------------------------------------------
// Maps common aliases to the canonical EFC names so we can validate and
// replace any data that doesn't match the source PDFs.
export const CLUB_ALIASES: Record<string, string> = {
  "Bayern Munich": "FC Bayern München",
  "Bayern München": "FC Bayern München",
  "FC Bayern Munich": "FC Bayern München",
  "Manchester City": "Manchester City FC",
  "Man City": "Manchester City FC",
  "Juventus": "Juventus FC",
  "Inter Milan": "FC Internazionale Milano",
  "Internazionale": "FC Internazionale Milano",
  "Inter": "FC Internazionale Milano",
};

export const COUNTRY_ALIASES: Record<string, string> = {
  "United Kingdom": "England",
  "UK": "England",
  "Great Britain": "England",
  "Britain": "England",
  // Non-EFC countries fall back to England so the data stays consistent
  "United States": "England",
  "USA": "England",
  "Senegal": "England",
};

const CLUB_BY_NAME: Record<string, EfcClub> = Object.fromEntries(
  EFC_CLUBS.map((c) => [c.name.toLowerCase(), c]),
);

export function normalizeClubName(name?: string): string {
  if (!name) return "";
  const aliased = CLUB_ALIASES[name] ?? name;
  const exact = CLUB_BY_NAME[aliased.toLowerCase()];
  return exact ? exact.name : aliased;
}

export function normalizeCountryName(name?: string): string {
  if (!name) return "";
  return COUNTRY_ALIASES[name] ?? name;
}

export interface NormalizedMember {
  country: string;
  team: string;
  region: string;
}

const FALLBACK = { country: "England", team: "Liverpool FC" };

/**
 * Returns canonical { country, team, region } for a member.
 * - If `team` matches an EFC club, that club's country is authoritative.
 * - If `country` is in EFC, region is derived from it.
 * - Anything that doesn't match the EFC source data is replaced with valid values.
 */
export function normalizeMember(rawCountry?: string, rawTeam?: string): NormalizedMember {
  const teamCanonical = normalizeClubName(rawTeam);
  const club = teamCanonical ? CLUB_BY_NAME[teamCanonical.toLowerCase()] : undefined;
  let country = normalizeCountryName(rawCountry);

  if (club) {
    country = club.country;
  } else if (!country || !COUNTRY_TO_REGION[country]) {
    country = FALLBACK.country;
  }

  let team = teamCanonical;
  if (!club) {
    const def = EFC_CLUBS.find((c) => c.country === country && c.gender === "Men");
    team = def?.name ?? FALLBACK.team;
  }

  const region = COUNTRY_TO_REGION[country] ?? COUNTRY_TO_REGION[FALLBACK.country];
  return { country, team, region };
}

// Deterministic color from string
const hashHue = (s: string): number => {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h % 360;
};

const initials = (name: string): string => {
  const cleaned = name.replace(/\(.*?\)/g, "").trim();
  const words = cleaned.split(/\s+/).filter((w) => !/^(FC|AC|FK|SK|SC|HC|HSK|HNK|NK|GNK|ZNK|ŽNK|KF|CF|UE|CE|FS|US|RC|RSC|KAA|KAS|KRC|KV|KVC|PFC|OFC|WFC|ZFK|SFC|HŠK|FF|FFK|MFK|MK|TFC|GFC)$/i.test(w));
  const target = words.length ? words : cleaned.split(/\s+/);
  return target
    .slice(0, 2)
    .map((w) => w.charAt(0).toUpperCase())
    .join("");
};

export const getTeamLogoFallback = (team: string): string => {
  const canonical = CLUB_ALIASES[team] ?? team ?? "";
  const hue = hashHue(canonical);
  const init = initials(canonical) || "FC";
  const bg = `hsl(${hue}, 65%, 45%)`;
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><circle cx='32' cy='32' r='30' fill='${bg}' stroke='white' stroke-width='2'/><text x='50%' y='52%' text-anchor='middle' dominant-baseline='middle' font-family='Inter,Arial,sans-serif' font-size='22' font-weight='700' fill='white'>${init}</text></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
};

export const getTeamLogo = (team: string): string => {
  if (!team) return "";
  const canonical = CLUB_ALIASES[team] ?? team;
  if (KNOWN_CLUB_LOGOS[canonical]) return KNOWN_CLUB_LOGOS[canonical];
  return getTeamLogoFallback(canonical);
};

export const getClubsByCountry = (country: string): EfcClub[] =>
  EFC_CLUBS.filter((c) => c.country === country);

export const getRegionByCountry = (country: string): string | undefined =>
  COUNTRY_TO_REGION[country];

export const getCountriesByRegion = (region: string): string[] =>
  EFC_COUNTRIES.filter((c) => c.region === region).map((c) => c.name);
